### ISSUE TITLE
Ditch incremental_dom, roll custom reconciliation

### ISSUE THREAD

**Issue by thosakwe** [mariposa-dart/mariposa#11]
Incremental DOM is relatively simple, but it is unmaintained, and almost entirely abandoned (nice...). A custom renderer would mean that nobody has to paste in the idom polyfill, and also can be maintained right along with Mariposa itself.

**Comment by brianegan** [comment]
Have you checked out the Butterfly lib? I found it also has a few issues when it comes to rendering, but might be a good source of inspiration for some of this.

**Comment by thosakwe** [comment]
Fast-forward to over a year later, and the state of things has really improved, especially because `package:universal_html` exists now. I have a basic idom implementation here (no unit tests just yet): https://github.com/mariposa-dart/mariposa/blob/2.x/packages/mariposa/lib/src/universal/universal_incremental_dom.dart

The `incremental_dom` project was revived, but I'm still going to try to ditch it, and go all-in on `UniversalIncrementalDom`.

**Comment by thosakwe** [comment]
After a little more careful thought, I think it makes sense to keep `incremental_dom` in the browser, where performance is most important. `package:mariposa/universal.dart` can still be used in the browser, though.
